#!/bin/sh
set -eu

cd "$(git rev-parse --show-toplevel)/web-game-elevator-pwo-react-pixi-js"
export VITE_BASE_PATH=/monorepo-colin/
# Git Bash must pass this URL path unchanged to Windows Node.
export MSYS2_ENV_CONV_EXCL=VITE_BASE_PATH

npm run check
npm test
