export const copy = {
  brand: 'COLINS VÄRLD',
  eyebrow: 'EN VÅNING I TAGET',
  title: 'Colins hissäventyr',
  titleName: 'Colins',
  titleAdventure: 'hissäventyr.',
  intro: 'Små fötter. Stora upptäckter.',
  description: 'En egen liten värld av hissar, knappar och nyfikna upptäckter.',
  play: 'Spela',
  about: 'Om spelet',
  close: 'Stäng',
  panelTitle: 'En värld att upptäcka',
  panelIntro: 'Följ med Colin på hissäventyr, i hans egen takt.',
  panelBody:
    'Åk hiss, tryck på knappar och utforska tre hus. Hjälp andra att åka med, prova den gamla grinden och tänd och släck lamporna. De gröna skyltarna visar vägen ut.',
  panelNote: 'Du bestämmer takten. Inga poäng, inga måsten. Spelet sparar var du är när du tar en paus.',
  footer: 'BARA DU, COLIN OCH NÄSTA VÅNING.',
  sceneLabel: 'Colin står barfota i en lugn lobby, bredvid en hiss och en dörr med grön utgångsskylt.',
  loading: 'Öppnar hisshallen…',
  edition: '01 — HISSÄVENTYRET',
  welcome: 'VÄLKOMMEN IN',
  floor: 'VÅNING 0',
  caption: 'En liten början på ett stort äventyr.',
} as const;
